export const adminConstants = {
  DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',

  COMMENTS_REVIEW_REQUEST: 'COMMENTS_REVIEW_REQUEST',
  COMMENTS_REVIEW_SUCCESS: 'COMMENTS_REVIEW_SUCCESS',
  COMMENTS_REVIEW_FAILURE: 'COMMENTS_REVIEW_FAILURE'
};