export const commentConstants = {
  ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',

  ALL_COMMENTS_REQUEST: 'ALL_COMENTS_REQUEST',
  ALL_COMMENTS_SUCCESS: 'ALL_COMMENTS_SUCCESS',
  ALL_COMMENTS_FAILURE: 'ALL_COMMENTS_FAILURE'
};