export const heroConstants = {
  GET_HEROES_REQUEST: 'GET_HEROES_REQUEST',
  GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
  GET_HEROES_FAILURE: 'GET_HEROES_FAILURE',

  GET_HERO_REQUEST: 'GET_HERO_REQUEST',
  GET_HERO_SUCCESS: 'GET_HERO_SUCCESS',
  GET_HERO_FAILURE: 'GET_HERO_FAILURE'
};