export const itemConstants = {
  GET_ITEMS_REQUEST: 'GET_ITEMS_REQUEST',
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  GET_ITEMS_FAILURE: 'GET_ITEMS_FAILURE',

  GET_ITEM_REQUEST: 'GET_ITEM_REQUEST',
  GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
  GET_ITEM_FAILURE: 'GET_ITEM_FAILURE'
};